[package]
name = "astromonitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minreq = { version = "2.4.2", features = ["https"] }
sysinfo = "0.22.3"
structopt = { version = "0.3", default-features = false }
